### ISSUE TITLE
Leipzig.pm.org needs content

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#132]
Re: #130: Hello @dboehmer. Can you take a look at your Github Pages setup? It seems to be 404. Thanks. :)

**Comment by dboehmer** [comment]
I didn't find time to look into this for some days but it's great to see that GitHub pages with custom domain supports HTTP since May 1st. https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Sorry for the changing requests but could you make `leipzig.pm.org` a CNAME to `leipzig-pm.github.io`?

These are the benefits why I do now prefer this solution:
* HTTPS can be used and enforced now
* no redirects
* no GitHub affiliation

The GitHub page is already set up to work like this. Can be tested via curl:

```
$ curl http://leipzig.pm.org/ --connect-to leipzig.pm.org:80:leipzig-pm.github.io:80
<html>
<body>

<h1>Hello $World</h1>

</body>
</html>
```

Once you set up DNS I can enable and enforce HTTPS at GitHub.

**Comment by jhannah** [comment]
^ @rspier

**Comment by jhannah** [comment]
I also created DNS request #133201 because I wasn't sure, on second reading, if this was a special case for Robert or a standard one.

**Comment by rspier** [comment]
Done.
This is a normal DNS ticket case.  I had to change the CNAME.

**Comment by dboehmer** [comment]
Thank you very much, @jhannah++ and @rspier++!

DNS seems all fine. The page is available but the certificate is only for github.com. I can't find anything wrong with the settings and sent a help request to GitHub (my first one ever).

**Comment by dboehmer** [comment]
I received a notification from friendly staff at GitHub that they fixed the issue and https://leipzig.pm.org/ is now available. We will set up actual content soon.

**Comment by jhannah** [comment]
@dboehmer ping :)  It's been a month, if you could get basic content in that'd be great. Just quick paragraph and links to mailing list would be fine for now.

**Comment by jhannah** [comment]
I deactivated your group. Ping us when you have a website up and we'll reactivate you. Thanks!

**Comment by dboehmer** [comment]
@jhannah Thanks for keeping an eye on the pages whether they are active or 404/… I've now set up a basic page. You'll see I'm not a designer but most important information are there. Because the DNS alias is currently missing I can't link to the page but you'll find the HTML at https://github.com/leipzig-pm/leipzig-pm/blob/master/index.html

Can you please reactivate leipzig.pm.org?

**Comment by jhannah** [comment]
XML updated and flushed to website, DNS request sent, should take in a day or so.

**Comment by jhannah** [comment]
@dboehmer yay! looks like it's working! :)
