### ISSUE TITLE
reCAPTCHA validation failed

### ISSUE THREAD

**Issue by ingydotnet** [perlorg/www.pm.org#173]
At https://mail.pm.org/mailman/listinfo/toronto-pm

Enter any email address in "Your email address:"
and any name in "Your name (optional):"
and click [Subscribe] button
and takes to a page that says:

toronto-pm Subscription results
reCAPTCHA validation failed: invalid-input-responsetoronto-pm Subscription results

----

I'm trying to subscribe to the toronto-pm list for ingy at ingy dot net
My pw manager says I have an account for mail.pm.org but I have know idea where to login to that.

Help appreciated :)

**Comment by rspier** [comment]
I can't replicate this.

What browser are you using?  Do you have any weird extensions enabled or other settings disabled?  Can you try a different browser?

mail.pm.org doesn't have traditional accounts -- each list gets its own password.

**Comment by ingydotnet** [comment]
@rspier Thanks for looking into this. Here are a couple screen shots showing what happens:

* https://pasteboard.co/049SlXd2dbT2.png
* Click the "Subscribe" button
* https://pasteboard.co/NcQCVKYSCivs.png

This happens on 6 different browsers on 2 machines, LInux and Mac, on 2 different networks.

What do you get?

**Comment by rspier** [comment]
I had tried with a test list, not toronto-pm.  Something is causing the recaptcha checkbox to not show up on the toronto-pm page.  Digging.

**Comment by rspier** [comment]
In 2011, the toronto-pm listinfo  page was updated from the default Mailman one to one that was slightly customized, but it did not contain the template tag needed to make the reCAPTCHA stuff work.  I don't remember exactly when we first enabled reCAPTCHA, but a small number of lists have likely been broken since then. This is the first time anyone has reported the issue.  I believe I have now moved all the customized files out of the way, and the reCAPTCHA checkbox is now showing up.  I've also confirmed that I can make a subscription request for toronto-pm.

Thanks for reporting!
